### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by celicoo** [nathanpeck/exiftool#14]
~ DELETED ~

**Comment by nathanpeck** [comment]
If exif is undefined that usually means you haven't installed `exiftool` on your system.

The `exif` value there is a process which is spawned here: https://github.com/nathanpeck/exiftool/blob/master/lib/exiftool.js#L20

You can debug by attempting to run `exiftool -h` in your command line. If you see something like:

'bash: exiftool: command not found'

that will confirm that you need to install the exiftool binary.

**Comment by celicooo** [comment]
That's not the problem. I'm passing 1000 files asynchronous. Maybe this could break exiftool, don't you think?
