### ISSUE TITLE
Sample code not working

### ISSUE THREAD

**Issue by gurpal2000** [nathanpeck/exiftool#15]
Hi,

node: 4.5.0
npm: 2.15.9
exiftool (ubuntu): 9.46

The code where the file is read first and metadata extracted works, but not the one with the filename directly specified. Am i missing something here? 

exif.metadata(data) - ok
exif.metadata(filename) - not ok

[ exiftoolVersionNumber: 9.46, error: 'Unknown file type' ]

thanks

**Comment by ajhsu** [comment]
Just ran into the same issue. 

According to the commit log, the feature that support for filepath was started from `0.0.4`:
https://github.com/nathanpeck/exiftool/commit/601d2cb42e857bf5416abfe0610ce8cf8e30be59
But the package version on npm still remains in `0.0.3`, thats why it will ran into problem with filepath parameter.
So the solution maybe simply update the package version on npm.
